Hospital_Management/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('accounts/signup/', Register.as_view(), name='signup'),
    path('accounts/login/', Login.as_view(), name='login'),
    path('accounts/logout/', Logout.as_view(), name='logout'),
    path('receptionist/', ReceptionistDashBoard.as_view(), name='ReceptionistDashBoard'),
    path('create-appointment/', CreateAppointment.as_view(), name='create-appointment'),
    path('patients/', Patients.as_view(), name='patients'),
    path('doctor/', DoctorDashBoard.as_view(), name='DoctorDashBoard'),
    path('patient-dashboard/', PatientDashboard.as_view(), name='patientDashboard'),
    path('my-records/', MyAppointmentRecord.as_view(), name='my-records'),
    path('filter-appointments/', appointment_filter, name='appointment_filter'),
    path('my-appointments/', MyAppointments.as_view(), name='my-appointments'),
    path('my-upcoming-appointments/', UpcomingAppointments.as_view(), name='upcoming-appointments'),
    path('my-appointments/delete/<int:pk>/', MyAppointments.as_view(), name='my-appointments'),
    path('patient/<int:pk>/', PatientDetail.as_view(), name='patient-detail'),
    path('new-patient/', NewPatient.as_view(), name='new-patient'),
    path('appointment-history/<int:pk>/', AppointmentHistory.as_view(), name='appointment-history'),
    path('appointments/', ViewAppointments.as_view(), name='view-appointments'),
    path('appointment/<int:appointment_id>/', AppointmentDetailView.as_view(), name='appointment_detail'),
    path('available-doctors/', AvailableDoctors.as_view(), name='available-doctors'),
    path('doctor/appointments/', DoctorAppointments.as_view(), name='doctor-appointments'),
    path('doctor/appointments/<int:pk>/', DoctorAppointments.as_view(), name='doctor-appointments'),
    path('doctor/patients/', DoctorPatients.as_view(), name='doctor-patients'),
    path('available-doctors/<str:date>/<str:start_time>/<str:end_time>/',  AvailableDoctors.as_view(), name='available-doctors')

]

Hospital_Management_App/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Hospital_Management.urls')),
    path('messaging/', include('Messaging.urls', namespace='messaging'))
]

Messaging/urls.py
from django.urls import path
from .views import Index, get_chat_messages, newChat, get_doctors
app_name = 'messaging'


urlpatterns = [
    path('', Index.as_view(), name='home'),
    path('new-chat/<int:sender>/<int:receiver>/', newChat, name='new-chat'),
    path('get_doctors/', get_doctors, name='get_doctors'),
    path("chats/<int:chat_id>/messages/", get_chat_messages, name="get_chat_messages"),
]

Hospital_Management/forms.py
from django.forms import ModelForm
from . import models
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm

from .models import Doctor


class PatientForm(ModelForm):
    class Meta:
        model = models.PatientDetails
        fields = ['address', 'height', 'age', 'weight', 'blood_type', 'patient', 'mobile',
                  'symptoms']


class Register(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = models.User
        fields = ['email', 'password1', 'password2', 'firstname', 'lastname']


class LoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField()


class DoctorAppForm(ModelForm):
    class Meta:
        model = models.Appointment
        fields = ['reason', 'date', 'start_time', 'end_time', 'patient', 'assigned_doctor', 'status']


class InvoiceForm(ModelForm):
    class Meta:
        model = models.Invoice
        fields = '__all__'


class StaffForm(ModelForm):
    class Meta:
        model = models.Staff
        fields = '__all__'


class DoctorForm(ModelForm):
    class Meta:
        model = models.Doctor
        fields = '__all__'


class ServiceForm(ModelForm):
    class Meta:
        model = models.Service
        fields = '__all__'


class AppointmentForm(ModelForm):
    class Meta:
        model = models.Appointment
        fields = ['reason', 'date', 'start_time', 'end_time', 'assigned_doctor', 'patient']

    def save(self, commit=True):
        instance = super().save(commit=False)
        try:
            instance.save()
        except Exception as e:
            self.add_error(None, str(e))
            return None
        return instance


class AppointmentFilterForm(forms.Form):
    APPOINTMENT_STATUS_CHOICES = [
        ('P', 'Pending'),
        ('A', 'Approved'),
        ('C', 'Completed'),
    ]
    date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    time = forms.TimeField(required=False, widget=forms.TextInput(attrs={'type': 'time'}))
    end_time = forms.TimeField(required=False, widget=forms.TextInput(attrs={'type': 'time'}))
    status = forms.ChoiceField(required=False, choices=APPOINTMENT_STATUS_CHOICES)
    doctor = forms.ModelChoiceField(required=False, queryset=Doctor.objects.all())
    reason = forms.CharField(required=False)

Hospital_Management/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from . import models
from django.http import HttpResponseRedirect
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import redirect
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import get_object_or_404
import datetime
from .forms import *
from django.http import JsonResponse, QueryDict
from django.views import generic, View
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group

def has_group(user, group_name):
    """ check if the user belongs to a particular group"""
    group = Group.objects.get(name=group_name)
    return True if group in user.groups.all() else False

@login_required(login_url='accounts/login')
def home(request):
    if has_group(request.user, 'Doctors'):
        template_name = 'dashboards/doctorDashboard.html'
    elif has_group(request.user, 'Patients'):
        template_name = 'dashboards/PatientDashBoard.html'
    elif has_group(request.user, 'Admin'):
        template_name = 'dashboards/AdminDashBoard.html'
    elif has_group(request.user, 'Receptionist'):
        template_name = 'dashboards/ReceptionistDashBoard.html'
    return render(request, template_name)

class Register(generic.CreateView):

    form_class = Register
    models = models.User
    success_url = 'admin-dashboard'
    template_name = 'signup.html'
    context_object_name = 'form'

    def get(self, request):
        if self.request.user.is_authenticated:
            form = Register
            return render(request, self.template_name, context={'form': form})


    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        # must have loaded the data using python manage.py loaddata groups.json!
        group = Group.objects.get(name='Patients')
        group.user_set.add(user)
        return super(Register, self).form_valid(form)

    def form_invalid(self, form):
        error = form.errors
        raise ValidationError(error)

class Login(View):
    form_class = LoginForm
    models = models.User
    template_name = 'signup.html'

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['email'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.success(request,'username or password incorret')
                return render(request, self.template_name, context={'form': form})

        message = form.errors
        return render(request, self.template_name, context={'form': form})


    def get(self, request):
        if self.request.user.is_authenticated:
            return redirect('home')
        return render(request, self.template_name,)


class Logout(View):
    template_file_name = 'login.html'
    def get(self, request):
        logout(request)
        return redirect('login')


class AdminDashBoard(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = ('Hospital_Mangement.add_log', )
    def get_queryset(self):
        current_date = datetime.date.today()
        days = datetime.timedelta(days=7)
        begin = current_date - days
        total_doctors = models.Doctor.objects.all().count
        admitted_patients = models.AdmittedPatient.objects.select_related('patient')
        admitted_patients_details = admitted_patients.filter(admission_date__range=[begin, current_date])
        total_patients = models.PatientDetails.objects.all().count
        daily_appointments = models.Appointment.objects.filter(date=current_date)
        admitted_patients_count = admitted_patients.count()
        due_appointments = models.Appointment.objects.filter(status='P', date=current_date).count()
        total_beds = models.Bed.objects.all().count()
        total_beds_in_use = models.Bed.objects.filter(in_use=True).count()

        myset = {
            'admitted_patients': admitted_patients,
            'admitted_patients_details': admitted_patients_details,
            'total_doctors': total_doctors,
            'total_beds': total_beds,
            'total_beds_in_use': total_beds_in_use,
            'total_patients': total_patients,
            'admitted_patients_count': admitted_patients_count,
            'appointments': due_appointments,
            'daily_appointments': daily_appointments,
        }

        return myset

    template_name = 'dashboards/AdminDashBoard.html'
    context_object_name = 'data'


class ReceptionistDashBoard(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = ('Hospital_Management.add_appointment', 'Hospital_Management.view_doctor',
                           'Hospital_Management.view_appointment', 'Hospital_Management.add_patient', 'Hospital_Management.change_patient', 'Hospital_Management.view_patient')

    context_object_name = 'patients'
    queryset = models.Appointment.objects.all()
    model = models.Appointment
    template_name = 'dashboards/ReceptionistDashBoard.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ReceptionistDashBoard, self).get_context_data(*args, **kwargs)
        context['appointments'] = models.Appointment.objects.filter(date=datetime.date.today())
        context['upcoming_appointments'] = models.Appointment.objects.filter(date__gt=datetime.date.today())
        return context


class CreateAppointment(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView,):
    permission_required = ('Hospital_Management.add_appointment', 'Hospital_Management.change_appointment')
    form_class = AppointmentForm
    template_name = 'appointment_templates/AppointmentForm.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['doctors'] = models.Schedule.objects.filter(Q(staff__role__rank='Doctor') |
                                                            Q(staff__role__rank='Head Doctor'))\
            .filter(day_of_the_week=datetime.date.today().weekday())
        context['patient'] = models.PatientDetails.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        query_string = request.body.decode('utf-8')
        data = QueryDict(query_string)
        form = AppointmentForm(data)
        if form.is_valid():
            date = form.cleaned_data['date']
            time = form.cleaned_data['start_time']
            end_time = form.cleaned_data['end_time']
            reason = form.cleaned_data['reason']
            doctor = form.cleaned_data['assigned_doctor']
            patient = form.cleaned_data['patient']
            appointment = models.Appointment.objects.create(date=date, start_time=time, end_time=end_time, reason=reason, assigned_doctor=doctor, patient=patient)
            appointment.save()
            return JsonResponse({'success': True})
        return JsonResponse({"success": False, 'errors': dict(form.errors.items())})


class ViewAppointments(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = 'Hospital_Management.view_appointment'
    queryset = models.Appointment.objects.all()
    template_name = 'appointment_templates/appointments.html'
    context_object_name = 'appointments'

    def get_context_data(self, *args, **kwargs):
        context = super(ViewAppointments, self).get_context_data(*args, **kwargs)
        context['appointments'] = models.Appointment.objects.filter(date__gte=datetime.date.today())
        return context


class AppointmentDetailView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ('Hospital_Management.delete_appointment', 'Hospital_Management.view_appointment', 'Hospital_Management.change_appointment')
    model = models.Appointment
    form_class = AppointmentForm

    def get(self, request, appointment_id):
        appointment = get_object_or_404(models.Appointment, pk=appointment_id)
        data = {
            'date': appointment.date,
            'status': appointment.get_status_display(),
            'patientName': f'{str(appointment.patient)}',
            'patientId': appointment.patient_id,
            'time': appointment.start_time,
            'end_time': appointment.end_time,
            'doctor': f'{str(appointment.assigned_doctor)}',
            'doctor_id': appointment.assigned_doctor.pk,
            'reason': appointment.reason,
        }
        return JsonResponse(data)

    def delete(self, request, appointment_id):
        appointment = get_object_or_404(models.Appointment, pk=appointment_id)
        appointment.delete()
        return JsonResponse({'success': 'Deleted'})

    def put(self, request, appointment_id):
        appointment = get_object_or_404(models.Appointment, pk=appointment_id)
        query_string = request.body.decode('utf-8')
        data = QueryDict(query_string)
        if 'status' in data:
            form = DoctorAppForm(data, instance=appointment)
        else:
            form = AppointmentForm(data, instance=appointment)

        if form.is_valid():

            existing_appointments = models.Appointment.objects.filter(
                assigned_doctor=appointment.assigned_doctor,
                date=appointment.date
            ).exclude(pk=appointment.pk)

            for existing_appointment in existing_appointments:
                if appointment.start_time < existing_appointment.end_time and \
                        appointment.end_time > existing_appointment.start_time:

Hospital_Management/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20,100,1,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <style>
    #wrapper {
      width: 100%;
      overflow-x: hidden;
    }
    #sidebar-wrapper {
      min-height: 100vh;
      margin-left: -15rem;
      -webkit-transition: margin .25s ease-out;
      -moz-transition: margin .25s ease-out;
      -o-transition: margin .25s ease-out;
      transition: margin .25s ease-out;
    }
    #sidebar-wrapper .sidebar-heading {
      padding: 0.875rem 1.25rem;
      font-size: 1.2rem;
    }
    #sidebar-wrapper .list-group {
      width: 15rem;
    }
    #page-content-wrapper {
      width: 100%;
      margin-left: 0;
    }
    #wrapper.toggled #sidebar-wrapper {
      margin-left: 0;
    }
    @media (min-width: 768px) {
      #sidebar-wrapper {
        margin-left: 0;
      }
      #page-content-wrapper {
        min-width: 0;
        width: 100%;
      }
      #wrapper.toggled #sidebar-wrapper {
        margin-left: -15rem;
      }
    }
  </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />

</head>
<body>
  <div class="d-flex" id="wrapper">
    <!-- Sidebar -->
    <div class="bg-white border-right" id="sidebar-wrapper">
      <div class="sidebar-heading p-4 font-bold text-xl">Admin Dashboard</div>
      <div class="list-group list-group-flush" id="sidebar-links">
        <a href="{% url 'home' %}" class="list-group-item list-group-item-action bg-white p-4 hover:bg-gray-300">Home</a>
        <a href="{% url 'ReceptionistDashBoard' %}" class="list-group-item list-group-item-action bg-white p-4 hover:bg-gray-300">ReceptionistDashBoard</a>
        <a href="{% url 'DoctorDashBoard' %}" class="list-group-item list-group-item-action bg-white p-4 hover:bg-gray-300">Doctor DashBoard</a>
        <a href="{% url 'patientDashboard' %}" class="list-group-item list-group-item-action bg-white p-4 hover:bg-gray-300">Patient DashBoard</a>
        <a href="../admin/" class="list-group-item list-group-item-action bg-white p-4 hover:bg-gray-300">Administrator Panel</a>
        <a href="{% url 'messaging:home' %}" class="list-group-item list-group-item-action bg-white p-4 hover:bg-gray-300">Chats</a>
        <a href="{% url 'logout' %}" class="list-group-item list-group-item-action bg-white p-4 hover:bg-gray-300">Logout</a>
      </div>
    </div>
      <div id="page-content-wrapper">
          <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
            <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>
          </nav>
{% block content %}
{% endblock %}
      </div>
  </div>
<!-- Bootstrap and Sidebar Toggle JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
    function highlightActiveLink() {
      const myDiv = document.getElementById('sidebar-links')
      const links = myDiv.querySelectorAll('a');

      var currentUrl = window.location.pathname;
      for (var i = 0; i < links.length; i++) {
        var linkUrl = links[i].getAttribute('href');

        if (currentUrl === linkUrl) {
          links[i].classList.add('current');
        } else {
          links[i].classList.remove('current');
        }
      }
    }

    window.onload = function() {
      highlightActiveLink();
    };

  </script>
</body>
</html>

Hospital_Management/templates/base/doctordashbase.html
<!DOCTYPE html>
<html lang="en">
<head>
 
    <meta charset="UTF-8">
     <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20,100,1,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <style>
    #wrapper {
      width: 100%;
      overflow-x: hidden;
    }
    #sidebar-wrapper {
      min-height: 100vh;
      margin-left: -15rem;
      -webkit-transition: margin .25s ease-out;
      -moz-transition: margin .25s ease-out;
      -o-transition: margin .25s ease-out;
      transition: margin .25s ease-out;
    }
    #sidebar-wrapper .sidebar-heading {
      padding: 0.875rem 1.25rem;
      font-size: 1.2rem;
    }
    #sidebar-wrapper .list-group {
      width: 15rem;
    }
    #page-content-wrapper {
      width: 100%;
      margin-left: 0;
    }
    #wrapper.toggled #sidebar-wrapper {
      margin-left: 0;
    }
    @media (min-width: 768px) {
      #sidebar-wrapper {
        margin-left: 0;
      }
      #page-content-wrapper {
        min-width: 0;
        width: 100%;
      }
      #wrapper.toggled #sidebar-wrapper {
        margin-left: -15rem;
      }
    }
#sidebar-links a.current {
  background-color: #ddd;
  display: block;
}
  </style>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />

</head>
<body>
 <div class="d-flex" id="wrapper">
    <!-- Sidebar -->
    <div class="bg-white border-right" id="sidebar-wrapper">
      <div class="sidebar-heading p-4 font-bold text-xl">Doctor's Dashboard</div>
      <div class="list-group list-group-flush" id="sidebar-links">
        <a href="{% url 'home' %}" class="list-group-item list-group-item-action p-4 hover:bg-gray-300" id="home-link">Home</a>
        <a href="{% url 'doctor-patients' %}" class="list-group-item list-group-item-action  p-4 hover:bg-gray-300" id="patientdetails-records">My Admitted Patients</a>
          <a href="{% url 'messaging:home' %}" class="list-group-item list-group-item-action p-4 hover:bg-gray-300">Chats</a>
        <a href="{% url 'logout' %}" class="list-group-item list-group-item-action p-4 hover:bg-gray-300">Logout</a>
      </div>
    </div>
      <div id="page-content-wrapper">
          <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
            <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>
          </nav>
{% block content %}
{% load static %}
{% endblock %}
      </div>
 </div>
 <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });

    function highlightActiveLink() {
      const myDiv = document.getElementById('sidebar-links')
      const links = myDiv.querySelectorAll('a');


      var currentUrl = window.location.pathname;
      for (var i = 0; i < links.length; i++) {
        var linkUrl = links[i].getAttribute('href');
        if (currentUrl === linkUrl) {
          links[i].classList.add('current');
        } else {
          links[i].classList.remove('current');
        }
      }
    }

    window.onload = function() {

       highlightActiveLink();
    };

  </script>
</body>
</html>